# Generated by Django 5.0.3 on 2024-06-01 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_name_of_responsible', models.CharField(blank=True, max_length=100, null=True, verbose_name='имя ответственного')),
                ('last_name_of_responsible', models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия ответственного')),
                ('patronymic_of_responsible', models.CharField(blank=True, max_length=100, null=True, verbose_name='отчество ответственного')),
                ('job_title_of_responsible', models.CharField(blank=True, max_length=100, null=True, verbose_name='должность ответственного')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='дополнительная информация')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Направление подготовки / специальность',
                'verbose_name_plural': 'Направления подготовки / специальности',
            },
        ),
        migrations.CreateModel(
            name='FileOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
            ],
            options={
                'verbose_name': 'Файл приказа',
                'verbose_name_plural': 'Файлы приказов',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='номер группы')),
                ('course_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='номер курса')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_teacher', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('number_of_vacancies', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='количество вакантных мест')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='дополнительная информация')),
                ('notification_order', models.BooleanField(default=False, verbose_name='уведомление о выходе приказов')),
                ('notification_schedule', models.BooleanField(default=False, verbose_name='уведомление о графике работы')),
                ('notification_protection', models.BooleanField(default=False, verbose_name='уведомление о защите')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
            },
        ),
        migrations.CreateModel(
            name='TypeOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Тип приказа',
                'verbose_name_plural': 'Типы приказов',
            },
        ),
        migrations.CreateModel(
            name='CompositionOfSEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год проведения')),
                ('chairman_of_SEC', models.BooleanField(default=False, verbose_name='председатель ГЭК')),
                ('member_of_SEC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_composition_of_SEC', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Состав ГЭК',
                'verbose_name_plural': 'Составы ГЭК',
            },
        ),
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='должность')),
                ('academic_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='ученая степень')),
                ('academic_degree', models.CharField(blank=True, max_length=200, null=True, verbose_name='ученое звание')),
                ('place_of_work', models.CharField(blank=True, max_length=200, null=True, verbose_name='место работы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рабочая информация',
                'verbose_name_plural': 'Рабочая информация',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_str', models.CharField(blank=True, max_length=300, null=True, verbose_name='собственная тема')),
                ('is_accepted_theme', models.BooleanField(blank=True, null=True, verbose_name='тема подтверждена')),
                ('is_accepted_request', models.BooleanField(blank=True, null=True, verbose_name='заявка подтверждена')),
                ('explanatory_note_submitted', models.BooleanField(default=False, verbose_name='сдана пояснительная записка')),
                ('publication_agree', models.BooleanField(default=False, verbose_name='согласие на публикацию')),
                ('teacher_review', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='отзыв оценка')),
                ('review', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='рецензия оценка')),
                ('implementation_act', models.BooleanField(default=False, verbose_name='акт внедрения')),
                ('plagiarism_report', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='антиплагиат %')),
                ('type_of_fqw', models.CharField(blank=True, max_length=200, null=True, verbose_name='вид вкр')),
                ('fqw_in_english', models.BooleanField(default=False, verbose_name='вкр на английском')),
                ('fqw_recommended', models.CharField(blank=True, max_length=200, null=True, verbose_name='вкр рекомендована')),
                ('special_conditions', models.CharField(blank=True, max_length=200, null=True, verbose_name='специальные условия')),
                ('preprotection_grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='оценка на предзащите')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='дополнительная информация')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_consultant', to=settings.AUTH_USER_MODEL, verbose_name='консультант')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='выпускник')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_teacher', to=settings.AUTH_USER_MODEL, verbose_name='руководитель')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='PersonalWorkProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_time', models.TimeField(blank=True, null=True)),
                ('serial_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='порядковый номер выступающего')),
                ('final_grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='итоговая оценка')),
                ('protocol_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='номер протокола')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='дополнительная информация')),
                ('work_protection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='общая защита')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.request', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'Индивидуальная защита работы',
                'verbose_name_plural': 'Индивидуальная защита работы',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fieldofstudy', verbose_name='направление подготовки')),
            ],
            options={
                'verbose_name': 'Профиль / специализация',
                'verbose_name_plural': 'Профили / специализации',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.specialty', verbose_name='специальность'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_student', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('record_book_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='номер зачетки')),
                ('access_contacts_agree', models.BooleanField(default=False, verbose_name='согласие на публикацию контактов')),
                ('average_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='средний балл')),
                ('notification_order', models.BooleanField(default=False, verbose_name='уведомление о выходе приказов')),
                ('notification_schedule', models.BooleanField(default=False, verbose_name='уведомление о графике работы')),
                ('notification_protection', models.BooleanField(default=False, verbose_name='уведомление о защите')),
                ('basis_of_study', models.CharField(blank=True, choices=[('за счет бюджетных ассигнований федерального бюджета', 'за счет бюджетных ассигнований федерального бюджета'), ('на условиях договора об оказании платных образовательных услуг', 'на условиях договора об оказании платных образовательных услуг')], max_length=100, null=True, verbose_name='основа обучения')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('year_of_prev_education_completion', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год окончания предыдущего образования')),
                ('form_of_prev_education', models.CharField(blank=True, max_length=200, null=True, verbose_name='форма предыдущего образования')),
                ('year_of_admission', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год поступления')),
                ('special_marks', models.TextField(blank=True, null=True, verbose_name='особые отметки')),
                ('number_of_debts', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год поступления')),
                ('certificate_of_curriculum_completion', models.DateField(blank=True, null=True, verbose_name='справка о выполнении учебного плана')),
                ('record_book_submitted', models.BooleanField(default=False, verbose_name='сдана зачетка')),
                ('diploma_with_honors', models.BooleanField(default=False, verbose_name='диплом с отличием')),
                ('application_for_postgraduate_leave', models.BooleanField(default=False, verbose_name='заявление на последипломный отпуск')),
                ('recommended_for_admission', models.CharField(blank=True, max_length=100, null=True, verbose_name='рекомендован к поступлению')),
                ('group_leader', models.BooleanField(default=False, verbose_name='староста')),
                ('level_of_education', models.CharField(blank=True, choices=[('бакалавриат', 'бакалавриат'), ('магистратура', 'магистратура')], max_length=100, null=True, verbose_name='уровень образования')),
                ('number_of_requests', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='количество поданных заявок')),
                ('form_of_education', models.CharField(blank=True, choices=[('очно', 'очно'), ('очно-заочно', 'очно-заочно'), ('заочно', 'заочно')], max_length=100, null=True, verbose_name='форма образования')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='учебная группа')),
            ],
            options={
                'verbose_name': 'Выпускник',
                'verbose_name_plural': 'Выпускники',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200, null=True, verbose_name='принадлежность к кафедре')),
                ('fqw_by_application', models.CharField(blank=True, max_length=200, null=True, verbose_name='вкр по заявке')),
                ('free', models.BooleanField(default=True, verbose_name='тема свободна')),
                ('by_student', models.BooleanField(default=False, verbose_name='предложена выпускником')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.company', verbose_name='принадлежность к компании')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='рецензент')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_teacher', to=settings.AUTH_USER_MODEL, verbose_name='принадлежность к руководителю')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='theme',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.theme', verbose_name='тема из списка'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='номер приказа')),
                ('date', models.DateField()),
                ('order_point', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='пункт приказа')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='дополнительная информация')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fileorder', verbose_name='файл приказа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='выпускник')),
                ('type_of_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.typeoforder', verbose_name='тип приказа')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
            },
        ),
        migrations.CreateModel(
            name='WorkProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('venue_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='номер пункта проведения')),
                ('audience_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='аудитория')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='дополнительная информация')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='учебная группа')),
            ],
            options={
                'verbose_name': 'Общая защита работы',
                'verbose_name_plural': 'Общая защита работы',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=200, verbose_name='название этапа')),
                ('start', models.DateField(blank=True, null=True, verbose_name='начало этапа')),
                ('end', models.DateField(verbose_name='конец этапа')),
                ('result', models.CharField(blank=True, max_length=200, null=True, verbose_name='результат выполнения этапа')),
                ('completion_mark', models.BooleanField(blank=True, null=True, verbose_name='отметка о выполнении')),
                ('absence', models.BooleanField(null=True, verbose_name='неявка')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.request', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работ',
            },
        ),
    ]
