# Generated by Django 5.0.3 on 2024-06-09 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalworkprotection',
            name='work_protection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workprotection', verbose_name='общая защита'),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_of_education',
            field=models.CharField(blank=True, choices=[('очная', 'очная'), ('очно-заочная', 'очно-заочная'), ('заочная', 'заочная')], max_length=100, null=True, verbose_name='форма образования'),
        ),
        migrations.AlterField(
            model_name='student',
            name='number_of_debts',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='количество долгов'),
        ),
    ]
